services:
  dockertest:
    image: ghcr.io/tommat-208/docker-test-ghcr:latest
    ports:
      - "8080:8080"
      - "8081:8081"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true  # Rimuove le vecchie immagini
      - WATCHTOWER_POLL_INTERVAL=15  # Controlla ogni 15 secondi  
    restart: unless-stopped
