name: Pull Test

on:
    pull_request:
        branches:
            - master

env:
    DB_SERVER: server
    DB_USER: user
    ID_CLIENTE: id_cliente

jobs:
    pull_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            
            # step per ottenere l'id cliente?

            - name: Ottieni versione dal tag
              id: get_version
              run: |
                VERSION=$(git describe --tags --always)
                echo "VERSION=${VERSION}" >> $GITHUB_ENV

            - name: Installa sqlcmd tool
              run: |
                sudo apt-get update
                sudo apt-get install -y mssql-tools

            - name: Inserimento record in SQL
              run: |
                sqlcmd -S ${{ env.DB_SERVER }} -U ${{ env.DB_USER }} -P ${{ secrets.DB_PASSWORD }} -d prova_clienti -Q "INSERT INTO installazione (id_cliente, data_installazione, versione) VALUES (${{ ID_CLIENTE }}, GETDATE(), '${{ env.VERSION }}')"

            - name: Docker Login
              run: |
                docker login --username tommat-208 --password ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} ghcr.io

            - name: Pull dell'immagine
              run: |
                docker pull ghcr.io/tommat-208/docker-test-ghcr:latest
    
            

